### ISSUE TITLE
RuntimeError in test

### ISSUE THREAD

**Issue by ramnoob** [Tencent/Real-SR#22]
Thx for the great suggestion!

The following error occurred during testing.
`RuntimeError: DataLoader worker (pid(s) 8448) exited unexpectedly`
Probably due to lack of memory.
This may be resolved by setting the `n_workers` of the Data_loader to 0.
How do I set `n_workers` during testing?
I would also like to know if there is a better way.

**Comment by ramnoob** [comment]
The details of the error are as follows.

RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Users\ramwi\Anaconda3\envs\RealSR\lib\site-packages\torch\utils\data\dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\ramwi\Anaconda3\envs\RealSR\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 49, in <module>
    for data in test_loader:
  File "C:\Users\ramwi\Anaconda3\envs\RealSR\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\Users\ramwi\Anaconda3\envs\RealSR\lib\site-packages\torch\utils\data\dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "C:\Users\ramwi\Anaconda3\envs\RealSR\lib\site-packages\torch\utils\data\dataloader.py", line 1138, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\ramwi\Anaconda3\envs\RealSR\lib\site-packages\torch\utils\data\dataloader.py", line 999, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 8448) exited unexpectedly

**Comment by ramnoob** [comment]
It's resolved!

codes/data/__init__.py
line24:
        `return torch.utils.data.DataLoader(dataset, batch_size=1, shuffle=False, num_workers=1, pin_memory=True)`
rewrite to
        `return torch.utils.data.DataLoader(dataset, batch_size=1, shuffle=False, num_workers=0, pin_memory=True)`

thx!
