### ISSUE TITLE
Corrupted_noise is empty?

### ISSUE THREAD

**Issue by zhandarui** [Tencent/Real-SR#35]
why Corrupted_noise is empty?，length is 0，run the code:python3 train.py -opt options/df2k/train_bicubic_noise.yml 
the error is :
Traceback (most recent call last):
  File "/home/user/data/lost+found/Real-SR/Real-SR-master/codes/train.py", line 241, in <module>
    main()
  File "/home/user/data/lost+found/Real-SR/Real-SR-master/codes/train.py", line 154, in main
    for _, train_data in enumerate(train_loader):
  File "/home/user/miniconda/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/user/miniconda/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/miniconda/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/user/data/lost+found/Real-SR/Real-SR-master/codes/data/LQGT_dataset.py", line 147, in __getitem__
    noise = self.noises[np.random.randint(0, len(self.noises))]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/mtrand.pyx", line 782, in numpy.random.mtrand.RandomState.randint
  File "numpy/random/_bounded_integers.pyx", line 1334, in numpy.random._bounded_integers._rand_int64
ValueError: high <= 0

**Comment by fe-jpg** [comment]
@zhandarui grttings,i have the same,could you please teach me whether the noise is empty but no error when i run the code.it just seems like the source image does not contain nosie that satisfy the requirement. (很好奇为什么我跑的代码收集噪声为空，但在其他图像上可以收集噪声，看起来似乎是dped的数据集源域不满足这个噪声条件，想文下您是如何解决这个问题的
)
